#!/bin/bash
NAME=bitrix_tasks
DIR=/var/www/vhosts/ai-softdev.com/api-bitrix-tasks.ai-softdev.com
USER=root
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error
exec /var/www/vhosts/ai-softdev.com/api-bitrix-tasks.ai-softdev.com/venv/bin/gunicorn app.main:app \
  --bind 0.0.0.0:10254 \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --log-level=$LOG_LEVEL \
  --log-file=$DIR/gunicorn_log.log